version: '3'
services:
  nginx:
    image: nginx:1.15
    ports:
      - 80:80
    volumes:
      - ./src:/usr/share/nginx/html
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
  php-fpm:
    build: ./php-fpm
    volumes:
      - ./src:/var/www/html
  mysql:
    image: mysql:5.7
    environment:
        MYSQL_DATABASE: laravue1
        MYSQL_ROOT_PASSWORD: password
        MYSQL_USER: laravue_user
        MYSQL_PASSWORD: password
        TZ: Asia/Tokyo
    ports:
        - 3306:3306
    volumes:
    - ./mysql/data:/var/lib/mysql
  redis:
    image: redis:latest
    ports:
      - 6379:6379
      